INSERT INTO [Materialy]([Nazvanie_materiala],[Cena],[Edinica_izmereniy]) VALUES('Труба профильная стальная 20x20x1,5x6','36000','тн')
INSERT INTO [Materialy]([Nazvanie_materiala],[Cena],[Edinica_izmereniy]) VALUES('Труба профильная стальная 25x25x1,5x6','43000','тн')
INSERT INTO [Materialy]([Nazvanie_materiala],[Cena],[Edinica_izmereniy]) VALUES('Труба профильная стальная 30x30x1,5x6','52000','тн')
INSERT INTO [Materialy]([Nazvanie_materiala],[Cena],[Edinica_izmereniy]) VALUES('Труба профильная стальная 40x20x1,5x6','53000','тн')
INSERT INTO [Materialy]([Nazvanie_materiala],[Cena],[Edinica_izmereniy]) VALUES('Труба профильная стальная 40x40x1,5x6','33000','тн')
INSERT INTO [Materialy]([Nazvanie_materiala],[Cena],[Edinica_izmereniy]) VALUES('Труба профильная стальная 50x50x2x6','33000','тн')
INSERT INTO [Materialy]([Nazvanie_materiala],[Cena],[Edinica_izmereniy]) VALUES('Труба профильная стальная 60x30x2x6','35000','тн')
INSERT INTO [Materialy]([Nazvanie_materiala],[Cena],[Edinica_izmereniy]) VALUES('Труба профильная стальная 80x40x2x6','33000','тн')
INSERT INTO [Materialy]([Nazvanie_materiala],[Cena],[Edinica_izmereniy]) VALUES('Сталь(Лист х/к Ст08пс) 0,5х1250х2500','30300','тн')
INSERT INTO [Materialy]([Nazvanie_materiala],[Cena],[Edinica_izmereniy]) VALUES('Сталь(Лист х/к Ст08пс) 0,8х1250х2500','30200','тн')
INSERT INTO [Materialy]([Nazvanie_materiala],[Cena],[Edinica_izmereniy]) VALUES('Сталь(Лист х/к Ст08пс) 1,5х1250х2500','30100','тн')
INSERT INTO [Materialy]([Nazvanie_materiala],[Cena],[Edinica_izmereniy]) VALUES('Сталь(Лист х/к Ст08пс) 2,0х1250х2500','31300','тн')
INSERT INTO [Materialy]([Nazvanie_materiala],[Cena],[Edinica_izmereniy]) VALUES('Лист Алюминиевый 1105 АН2 0,5х1200х2000','124','кг')
INSERT INTO [Materialy]([Nazvanie_materiala],[Cena],[Edinica_izmereniy]) VALUES('Лист Алюминиевый 1105 АМ 0,6х1200х3000','100','кг')
INSERT INTO [Materialy]([Nazvanie_materiala],[Cena],[Edinica_izmereniy]) VALUES('Лист Алюминиевый 1105 АМ 0,8х1200х2000','82','кг')
INSERT INTO [Materialy]([Nazvanie_materiala],[Cena],[Edinica_izmereniy]) VALUES('Швеллер стальной 2,5-5','22000','тн')
INSERT INTO [Materialy]([Nazvanie_materiala],[Cena],[Edinica_izmereniy]) VALUES('Полипропилен РР-С 10мм 3000х1500х10','41.5','шт')
INSERT INTO [Materialy]([Nazvanie_materiala],[Cena],[Edinica_izmereniy]) VALUES('Полипропилен РР-Н 15 мм 3000х1500х15','65.2','шт')
INSERT INTO [Materialy]([Nazvanie_materiala],[Cena],[Edinica_izmereniy]) VALUES('шасси','300000','шт')
INSERT INTO [Materialy]([Nazvanie_materiala],[Cena],[Edinica_izmereniy]) VALUES('кабина','90000','шт')
INSERT INTO [Materialy]([Nazvanie_materiala],[Cena],[Edinica_izmereniy]) VALUES('промежуточный редуктор','175000','шт')
INSERT INTO [Materialy]([Nazvanie_materiala],[Cena],[Edinica_izmereniy]) VALUES('механизм поворота','50000','шт')
INSERT INTO [Materialy]([Nazvanie_materiala],[Cena],[Edinica_izmereniy]) VALUES('стабилизатор','5250','шт')
INSERT INTO [Materialy]([Nazvanie_materiala],[Cena],[Edinica_izmereniy]) VALUES('коробка отбора мощности','28000','шт')
INSERT INTO [Materialy]([Nazvanie_materiala],[Cena],[Edinica_izmereniy]) VALUES('лебедка','61000','шт')
INSERT INTO [Materialy]([Nazvanie_materiala],[Cena],[Edinica_izmereniy]) VALUES('гидравлическое устройство подъема невыдвижной стрелы','94000','шт')
INSERT INTO [Materialy]([Nazvanie_materiala],[Cena],[Edinica_izmereniy]) VALUES('гидравлическое устройство выдвижной стрелы(средней)','90000','шт')
INSERT INTO [Materialy]([Nazvanie_materiala],[Cena],[Edinica_izmereniy]) VALUES('гидравлическое устройство выдвижной дополнительной стрелы','85000','шт')
INSERT INTO [Materialy]([Nazvanie_materiala],[Cena],[Edinica_izmereniy]) VALUES('реверсивно-распределительный механизм','53000','шт')
INSERT INTO [Materialy]([Nazvanie_materiala],[Cena],[Edinica_izmereniy]) VALUES('ограничитель грузоподъемности','7500','шт')
INSERT INTO [Materialy]([Nazvanie_materiala],[Cena],[Edinica_izmereniy]) VALUES('гидромотор лебедки','70000','шт')
INSERT INTO [Materialy]([Nazvanie_materiala],[Cena],[Edinica_izmereniy]) VALUES('крюк','32000','шт')
INSERT INTO [Materialy]([Nazvanie_materiala],[Cena],[Edinica_izmereniy]) VALUES('грузовой трос','300','м')
INSERT INTO [Materialy]([Nazvanie_materiala],[Cena],[Edinica_izmereniy]) VALUES('болт крепления ОПУ М20*160','136','шт')
INSERT INTO [Materialy]([Nazvanie_materiala],[Cena],[Edinica_izmereniy]) VALUES('болт крепления ОПУ М10*50','50','шт')




--gj\\поставщики
INSERT INTO [Postavhik] ([Naimenovanie],[Adres],[Phone],[Nomer_scheta]) VALUES('ОАО Клевер','Иваново, ул. Строителей, д. 5','2-56-95','40702810654582100000')
INSERT INTO [Postavhik] ([Naimenovanie],[Adres],[Phone],[Nomer_scheta]) VALUES('ЗАО Промстрой','Кострома, пр. Мира, д. 22','5-65-87','40702810596465900000')
INSERT INTO [Postavhik] ([Naimenovanie],[Adres],[Phone],[Nomer_scheta]) VALUES('ЗАО Промметалл','Нижний Новгород, ул. Калинина, д. 85','5-65-00','40702840855562400000')
INSERT INTO [Postavhik] ([Naimenovanie],[Adres],[Phone],[Nomer_scheta]) VALUES('ЗАО СтальИнвест','Шуя, ул. Карла Маркса, д. 8','6-65-60','40702810548930200000')
INSERT INTO [Postavhik] ([Naimenovanie],[Adres],[Phone],[Nomer_scheta]) VALUES('ОАО ЭкспоПрофи','Ковров, ул. Победы, д. 65','2-50-53','40702810952645800000')
INSERT INTO [Postavhik] ([Naimenovanie],[Adres],[Phone],[Nomer_scheta]) VALUES('ОАО Унимакс','Вологда, ул. Пролетарская, д. 46','4-25-80','40702810983023400000')
INSERT INTO [Postavhik] ([Naimenovanie],[Adres],[Phone],[Nomer_scheta]) VALUES('ЗАО Север','Торжок, ул. Финансистов, д. 6','1-53-52','40702840031215500000')
INSERT INTO [Postavhik] ([Naimenovanie],[Adres],[Phone],[Nomer_scheta]) VALUES('ЗАО Мичиган','Ярославль, ул. Правдиной, д. 79','8-52-10','40702840984521000000')
INSERT INTO [Postavhik] ([Naimenovanie],[Adres],[Phone],[Nomer_scheta]) VALUES('ЗАО Фурия','Лакинск, ул. Советская, д. 90','9-45-80','40702810569521000000')
INSERT INTO [Postavhik] ([Naimenovanie],[Adres],[Phone],[Nomer_scheta]) VALUES('ЗАО ИвПром','Иваново, ул. Калинина, д. 88','2-35-93','40702810989563000000')
INSERT INTO [Postavhik] ([Naimenovanie],[Adres],[Phone],[Nomer_scheta]) VALUES('ЗАО Молния','Киров, ул. Восточная, д. 20','3-52-21','40702840560215100000')
INSERT INTO [Postavhik] ([Naimenovanie],[Adres],[Phone],[Nomer_scheta]) VALUES('ЗАО Индекс','Приволжск, ул. 2-я Набережная, д. 56','2-91-00','40702810954585100000')
INSERT INTO [Postavhik] ([Naimenovanie],[Adres],[Phone],[Nomer_scheta]) VALUES('ЗАО Сухостой','Москва, ул. Посадская, д. 7','3-00-83','40702810569563200000')
INSERT INTO [Postavhik] ([Naimenovanie],[Adres],[Phone],[Nomer_scheta]) VALUES('ЗАО Магнит','Ростов, ул. Анисовая, д. 49','5-64-20','40702840302352100000')
INSERT INTO [Postavhik] ([Naimenovanie],[Adres],[Phone],[Nomer_scheta]) VALUES('ЗАО Фанера','Фурманов, ул. Курочкина, д. 31','7-35-54','40702840612021200000')
INSERT INTO [Postavhik] ([Naimenovanie],[Adres],[Phone],[Nomer_scheta]) VALUES('ООО Прометей','Обнинск, ул. Ленина, д.5 ','78-65-42','384975861882')
INSERT INTO [Postavhik] ([Naimenovanie],[Adres],[Phone],[Nomer_scheta]) VALUES('ЗАО Адмирал','Мурманск, ул. Московская, д.4 ','56-777-13','78965165896326')
INSERT INTO [Postavhik] ([Naimenovanie],[Adres],[Phone],[Nomer_scheta]) VALUES('ОАО Зевс','Брянск, первое шоссе, ст. 2','555-76-23','54781258799')
INSERT INTO [Postavhik] ([Naimenovanie],[Adres],[Phone],[Nomer_scheta]) VALUES('ЗАО Грань','Владимир, ул. Муромская, д.3 ','213-543','111258952463')
INSERT INTO [Postavhik] ([Naimenovanie],[Adres],[Phone],[Nomer_scheta]) VALUES('ОАО Полет','Заволжск, ул. Островского, д.4','896-333-01','789545022214444')
INSERT INTO [Postavhik] ([Naimenovanie],[Adres],[Phone],[Nomer_scheta]) VALUES('ЗАО РосСталь','Кинешма, ул. Вичугская, д.5','45-56-03','777789990263641')
INSERT INTO [Postavhik] ([Naimenovanie],[Adres],[Phone],[Nomer_scheta]) VALUES('ООО Пулемет','Голицыно, Можайское шоссе, ст. 3','58-79-31','4445869723')
INSERT INTO [Postavhik] ([Naimenovanie],[Adres],[Phone],[Nomer_scheta]) VALUES('ОАО Колизей','Одинцово, ул. Приезжая, д. 78','569-895','478526321179')
INSERT INTO [Postavhik] ([Naimenovanie],[Adres],[Phone],[Nomer_scheta]) VALUES('ЗАО Три Кита','Тверь, ул. Орлова, д. 34','564-23-32','566789920')
INSERT INTO [Postavhik] ([Naimenovanie],[Adres],[Phone],[Nomer_scheta]) VALUES('ОАО Скумбрия','Муром, ул. Владимирская, д. 54','895-45-78','7899214505')
INSERT INTO [Postavhik] ([Naimenovanie],[Adres],[Phone],[Nomer_scheta]) VALUES('ИП Симакина','Вичуга, ул. Фролова, д. 9','258-654','12547899632258')
INSERT INTO [Postavhik] ([Naimenovanie],[Adres],[Phone],[Nomer_scheta]) VALUES('ООО МашТех','Родники, ул. Ивановская, д. 76','324-58-76','147869252586335')
INSERT INTO [Postavhik] ([Naimenovanie],[Adres],[Phone],[Nomer_scheta]) VALUES('ЗАО Гигант','Ярославль, ул. Петра первого, д. 3','25-31-70','85964732324899')
INSERT INTO [Postavhik] ([Naimenovanie],[Adres],[Phone],[Nomer_scheta]) VALUES('ОАО Лилипут','Санкт-Петербург, ул. Пролетарская, д. 7','96-58-71','254879996558444')
INSERT INTO [Postavhik] ([Naimenovanie],[Adres],[Phone],[Nomer_scheta]) VALUES('ООО Трио','Балашиха, шоссе Энтузиастов, ст. 93','78-54-13','888555779933156000')
INSERT INTO [Postavhik] ([Naimenovanie],[Adres],[Phone],[Nomer_scheta]) VALUES('ОАО Бугага','Омск, ул. Железнодорожная, д.15','54-13-40','85479126473984200000')
INSERT INTO [Postavhik] ([Naimenovanie],[Adres],[Phone],[Nomer_scheta]) VALUES('ООО Магнит','Калининград, ул. Зеленая, д.76','47-52-78','25418596365748000000')
INSERT INTO [Postavhik] ([Naimenovanie],[Adres],[Phone],[Nomer_scheta]) VALUES('ЗАО Империя стали','Тарабыкино, ул. Первомайская, д.65','75-96-31','12325262428495700000')
INSERT INTO [Postavhik] ([Naimenovanie],[Adres],[Phone],[Nomer_scheta]) VALUES('ООО Суровый болт','Челябинск, ул. Жесткая, д.13','84-54-12','30759486389421500000')
INSERT INTO [Postavhik] ([Naimenovanie],[Adres],[Phone],[Nomer_scheta]) VALUES('ОАО Тамбовский волк','Тамбов, ул.Волков, д.34','96-65-36','78512469923457600000')
INSERT INTO [Postavhik] ([Naimenovanie],[Adres],[Phone],[Nomer_scheta]) VALUES('ЗАО Андромеда','Ярославль, Космонавтов, д.52','41-87-56','20504789612435800000')
INSERT INTO [Postavhik] ([Naimenovanie],[Adres],[Phone],[Nomer_scheta]) VALUES('ООО Кольцо Всевластия','Саранск, ул. Братская, д.53','21-85-87','87945625896374100000')
INSERT INTO [Postavhik] ([Naimenovanie],[Adres],[Phone],[Nomer_scheta]) VALUES('ЗАО ПромСтройМеталл','Псков, ул. Райская, д.43','45-65-12','79562138413056900000')
INSERT INTO [Postavhik] ([Naimenovanie],[Adres],[Phone],[Nomer_scheta]) VALUES('ОАО ЖИМ','Элиста, ул.Спортивная, д.13','51-32-47','85236974115975300000')
INSERT INTO [Postavhik] ([Naimenovanie],[Adres],[Phone],[Nomer_scheta]) VALUES('ЗАО Карма','Пенза, Проспект Мухи, д.87','12-65-84','30102045951267800000')
INSERT INTO [Postavhik] ([Naimenovanie],[Adres],[Phone],[Nomer_scheta]) VALUES('ООО РусМед','Сыктывкар, шоссе Дальнее','65-41-27','10504695784231500000')
INSERT INTO [Postavhik] ([Naimenovanie],[Adres],[Phone],[Nomer_scheta]) VALUES('ЗАО Вече','Великий Новгород, ул. Бояр, д.75','87-65-92','54126230759481200000')
INSERT INTO [Postavhik] ([Naimenovanie],[Adres],[Phone],[Nomer_scheta]) VALUES('ОАО Доцент','Ижевск, ул. Оранжевая, ул.Торжковская, д.61','85-42-31','30617592436184700000')
INSERT INTO [Postavhik] ([Naimenovanie],[Adres],[Phone],[Nomer_scheta]) VALUES('ООО Перевозчик','Магадан, ул.Лысых, д.69','66--67-77','16487592324568500000')
INSERT INTO [Postavhik] ([Naimenovanie],[Adres],[Phone],[Nomer_scheta]) VALUES('ЗАО Комплект','Тагил, ул. Эльбрус, д.87','23-84-65','8106235489365170000')
INSERT INTO [Postavhik] ([Naimenovanie],[Adres],[Phone],[Nomer_scheta]) VALUES('ООО Металл','Приволжск, ул. 1-я Маяковская д.23','34-76-32','39468242763482000000')
INSERT INTO [Postavhik] ([Naimenovanie],[Adres],[Phone],[Nomer_scheta]) VALUES('ООО Железяка','Шуя, ул. Кооперативная д. 3','22-43-43','39468242705365800000')
INSERT INTO [Postavhik] ([Naimenovanie],[Adres],[Phone],[Nomer_scheta]) VALUES('ООО КранAll','Нижний Новгород, ул. Зеленая д. 234','12-54-74','39468272964462300000')
INSERT INTO [Postavhik] ([Naimenovanie],[Adres],[Phone],[Nomer_scheta]) VALUES('ОАО Донецк','Лакинск, ул. Советов, д. 9','54-24-66','39468242657830100000')
INSERT INTO [Postavhik] ([Naimenovanie],[Adres],[Phone],[Nomer_scheta]) VALUES('ЗАО Метал у Васи','Шуя, ул. Калинина, д. 45','12-23-24','39468243061545700000')
INSERT INTO [Postavhik] ([Naimenovanie],[Adres],[Phone],[Nomer_scheta]) VALUES('ЗАО Железный человек','Вичуга, ул. Южная, д. 5','11-22-33','39468243091923300000')
INSERT INTO [Postavhik] ([Naimenovanie],[Adres],[Phone],[Nomer_scheta]) VALUES('ЗАО Тони Старк ','Голицыно, Ул. Маяковского, д. 66','34-23-42','39468272140115400000')
INSERT INTO [Postavhik] ([Naimenovanie],[Adres],[Phone],[Nomer_scheta]) VALUES('ООО Суперсталь','Одинцово, ул. Северная, д. 7','44-23-42','39468273093420900000')
INSERT INTO [Postavhik] ([Naimenovanie],[Adres],[Phone],[Nomer_scheta]) VALUES('ООО АРЖУ','Муром, ул. Верхняя, д. 54','22-44-52','39468242678420900000')
INSERT INTO [Postavhik] ([Naimenovanie],[Adres],[Phone],[Nomer_scheta]) VALUES('ООО ЖНКР','Ковров, ул. Тон, д. 77','56-62-26','39468243098462900000')
INSERT INTO [Postavhik] ([Naimenovanie],[Adres],[Phone],[Nomer_scheta]) VALUES('ЗАО МеталКран','Кострома, пр. Мун, д. 12','22-62-25','39468272669115000000')
INSERT INTO [Postavhik] ([Naimenovanie],[Adres],[Phone],[Nomer_scheta]) VALUES('ЗАО МеталБолт','Иваново, ул. Мира, д. 98','25-55-28','39468243063485000000')
INSERT INTO [Postavhik] ([Naimenovanie],[Adres],[Phone],[Nomer_scheta]) VALUES('ООО Тотем','Иваново, ул. Российская, д. 8','76-98-90','39468242678463100000')
INSERT INTO [Postavhik] ([Naimenovanie],[Adres],[Phone],[Nomer_scheta]) VALUES('ООО Кранекс','Родники, ул. Заграничная, д. 4','90-90-90','39468272411252000000')
INSERT INTO [Postavhik] ([Naimenovanie],[Adres],[Phone],[Nomer_scheta]) VALUES('ООО РосКран','Заволжск, ул. Горничная, д.9','89-89-89','39468272720921100000')



----материал поставщиков
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('15','63')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('16','64')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('6','65')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('7','66')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('8','67')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('9','68')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('10','69')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('11','70')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('12','71')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('13','72')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('14','73')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('15','74')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('16','75')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('17','76')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('18','77')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('19','78')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('20','79')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('21','80')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('22','81')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('23','82')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('24','83')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('25','84')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('26','85')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('27','86')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('28','87')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('29','88')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('30','89')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('31','90')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('32','91')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('33','92')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('34','93')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('35','94')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('36','95')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('37','96')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('38','97')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('39','98')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('40','99')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('6','100')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('7','101')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('8','102')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('9','103')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('10','104')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('11','105')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('12','106')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('13','107')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('14','108')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('15','109')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('16','110')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('17','111')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('18','112')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('19','113')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('20','114')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('21','115')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('22','116')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('23','117')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('24','118')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('25','119')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('26','120')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('27','121')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('28','122')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('29','63')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('30','64')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('31','65')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('32','66')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('33','67')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('34','68')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('35','69')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('36','70')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('37','71')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('38','72')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('39','73')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('40','74')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('6','75')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('7','76')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('8','77')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('9','78')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('10','79')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('11','80')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('12','81')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('13','82')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('14','83')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('15','84')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('16','85')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('17','86')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('18','87')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('19','88')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('20','89')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('21','90')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('22','91')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('23','92')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('24','93')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('25','94')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('26','95')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('27','96')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('28','97')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('29','98')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('30','99')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('31','100')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('32','101')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('33','102')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('34','103')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('35','104')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('36','105')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('37','106')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('38','107')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('39','108')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('40','109')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('6','110')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('7','111')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('8','112')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('9','113')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('10','114')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('11','115')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('12','116')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('13','117')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('14','118')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('15','119')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('16','120')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('17','121')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('18','122')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('19','63')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('20','64')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('21','65')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('22','66')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('23','67')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('24','68')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('25','69')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('26','70')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('27','71')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('28','72')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('29','73')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('30','74')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('31','75')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('32','76')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('33','77')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('34','78')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('35','79')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('36','80')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('37','81')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('38','82')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('39','83')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('40','84')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('6','85')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('7','86')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('8','87')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('9','88')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('10','89')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('11','90')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('12','91')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('13','92')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('14','93')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('15','94')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('16','95')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('17','96')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('18','97')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('19','98')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('20','99')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('21','100')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('22','101')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('23','102')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('24','103')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('25','104')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('26','105')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('27','106')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('28','107')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('29','108')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('30','109')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('31','110')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('32','111')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('33','112')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('34','113')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('35','114')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('36','115')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('37','116')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('38','117')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('39','118')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('40','119')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('6','120')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('7','121')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('8','122')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('9','97')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('10','98')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('11','99')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('12','100')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('13','101')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('14','102')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('15','103')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('16','104')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('17','105')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('18','106')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('19','107')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('20','108')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('21','109')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('22','70')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('23','71')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('24','72')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('25','73')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('26','74')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('27','75')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('28','76')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('29','77')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('30','78')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('31','79')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('32','80')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('33','81')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('34','82')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('35','83')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('36','84')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('37','85')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('38','86')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('39','87')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('40','88')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('35','89')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('36','90')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('37','91')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('38','70')
INSERT INTO [Material_u_postavhikov] ([ID_materiala],[ID_postavhika]) VALUES('39','71')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('40','72')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('6','73')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('7','74')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('8','75')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('9','76')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('10','77')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('11','78')
INSERT INTO [Material_u_postavhikov]([ID_materiala],[ID_postavhika]) VALUES('12','79')
